from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['atomic_riscv.c']
src += ['context_gcc.S']
src += ['cpuport.c']
src += ['interrupt_gcc.S']
src += ['interrupt_gcc.S']
src += ['interrupt.c']

group = DefineGroup('libcpu', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
