from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['startup.S']
src += ['interrupt_gcc.S']
src += ['context_gcc.S']
src += ['cpuport.c']
src += ['system.c']
src += ['trap.c']
src += ['vectors.S']

group = DefineGroup('sys', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
