from building import *

cwd = GetCurrentDir()
src = []

src += ['drv_timer.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_uart_v2.c']

if GetDepend('BSP_USING_PINMUX'):
    src += ['drv_pinmux.c']

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_CAN'):
    src += ['drv_can.c']

objs = DefineGroup('drivers', src, depend=[''], CPPPATH=[cwd])

Return('objs')
